test:
        image: isciences/exactextract-build-env:latest
        script:
                - mkdir build-master
                - cd build-master
                - cmake ..
                - make catch_tests
                - ./catch_tests

test-legacy:
        image: isciences/exactextract-build-env:geos36
        script:
                - mkdir build-master
                - cd build-master
                - cmake ..
                - make catch_tests
                - ./catch_tests

