image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: isciences/exactextract:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: isciences/exactextract:latest

# The build stage includes running of the unit tests
# We run them here so that we can delete the project
# sources and test executables after we're done.
build:
  stage: build
  script:
    - docker login -u ci4isciences -p $DOCKERHUB_PW
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

# The "test" stage just includes an additional test run
# against an older version of GEOS. Testing against
# current GEOS is done in the build stage.
test-legacy:
  stage: test
  image: isciences/exactextract-build-env:geos36
  script:
    - mkdir build-master
    - cd build-master
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make catch_tests
    - ./catch_tests

coverage:
  stage: release
  image: isciences/exactextract-build-env:latest
  script:
    - mkdir build-coverage
    - cd build-coverage
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..
    - make catch_tests
    - ./catch_tests
    - bash <(curl -s https://codecov.io/bash)

#    - apt-get update
#    - apt-get install -y lcov
#    - lcov --capture --directory CMakeFiles --output-file coverage.info

release-image:
  stage: release
  script:
    - docker login -u ci4isciences -p $DOCKERHUB_PW
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

  only:
    - master

